spring:
    dubbo:
      application:
        name: springboot-dubbo-provider
      registry:
        address: zookeeper://127.0.0.1:2181
      protocol:
        name: dubbo
        port: 20880
      scan: com.wxmclub.demo.springboot.dubbo.provider.service
