spring:
  # 数据源配置
  datasource:
    test:
      name: test
      url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
      username: root
      password: 123
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      # 监控统计拦截的filters
      filters: stat
      # 初始化大小、最小、最大
      initialSize: 1
      minIdle: 30
      maxActive: 300
      # 获取连接等待超时的时间,单位是毫秒
      maxWait: 60000
      # 间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    test2:
      name: test2
      url: jdbc:mysql://127.0.0.1:3306/test2?characterEncoding=utf8&useSSL=false
      username: root
      password: 123
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      # 监控统计拦截的filters
      filters: stat
      # 初始化大小、最小、最大
      initialSize: 1
      minIdle: 30
      maxActive: 300
      # 获取连接等待超时的时间,单位是毫秒
      maxWait: 60000
      # 间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:/com/wxmclub/demo/springboot/mybatis/dao/mapper/**/*.xml
  type-aliases-package: com.wxmclub.demo.springboot.mybatis.dao.model.**.*
